<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDe7xh7n\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDe7xh7n/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDe7xh7n.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDe7xh7n\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDe7xh7n\App_KernelDevDebugContainer([
    'container.build_hash' => 'De7xh7n',
    'container.build_id' => '414d5ab0',
    'container.build_time' => 1710434658,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDe7xh7n');
